#!/bin/env bash

if [[ -z "$@" ]]; then
   printf "Generate keys with given name,\nwith custom expiration date\nand export it to pkcs12 format\n\n Usage: $0 <cert_name> <days_to_expire> <nopass to gen without password> \n(for example: $0 users.navigat.ru 30 nopass)\n"
      exit 1
fi

days="${2:-30}"
nopass="${3:false}"

read latest_ip < latest_ip.txt
declare -i current_ip=($latest_ip)



if [[ "${nopass}" = "nopass" ]]; then
  ./easyrsa --days="${days}" build-client-full  "${1}" "nopass"
  ./easyrsa export-p12 "${1}" "nopass"
else
  ./easyrsa --days="${days}" build-client-full  "${1}" "nopass"
  ./easyrsa export-p12 "${1}"
fi
current_ip=$current_ip+1

if [ $? = 0 ]; then
  echo "ifconfig-push 10.11.162.${current_ip} 255.255.255.0" > "/etc/openvpn/auto_gen_ccd_files/${1}"
  echo -e 'push "dhcp-option DNS 10.10.16.1"\npush "dhcp-option DOMAIN navigator.private"' >> "/etc/openvpn/auto_gen_ccd_files/${1}"
  echo -e 'comp-lzo yes\npush "comp-lzo yes"\n' >> "/etc/openvpn/auto_gen_ccd_files/${1}"
  echo 'push "10.10.16.0 255.255.255.0"' >> "/etc/openvpn/auto_gen_ccd_files/${1}"
  echo $current_ip > latest_ip.txt

fi
./easyrsa gen-crl


echo "---> RESULTS in pki/private"